spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/taskmanager?useSSL=false&serverTimezone=UTC"
    username: root
    password: "Tokitoclaude0907@"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
